### ISSUE TITLE
Support Array type

### ISSUE THREAD

**Issue by N9vn1njdf** [Pietrum/GodotBS#1]
Hello. I'm using this package for my game. Thanks for this library. 
Tell me if there will be support for arrays. I really need it

**Comment by Fulkman** [comment]
Yes. I already made small project refresh and made last changes into support raw array.
If everything goes well in the next 24 h i will release version 1.4 with raw array support.

I want to add proper testing.
Can you send me your basic use cases of what exactly you want to do?
I will do all I can that it will be supported with 100%.

**Comment by N9vn1njdf** [comment]
Cool! 

My case is nothing unusual. 
Array of numbers and array of objects. Something like that:
[16,12,82,5,10,8]. Or [{key: boolean}, {key: number, key: string}]

**Comment by Fulkman** [comment]
Support for Array has been added.

Update library and make sure you have version 0.1.4 installed.
Waiting for feedback if everything works as expected.

**Comment by N9vn1njdf** [comment]
Cool, it's working. Thanks!
